services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
  mysql:
    image: mysql:8
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  backend:
    build:
      context: ./backend
      dockerfile: dev-dockerfile
    image: app-backend:dev
    command: ["./backend/tools/wait-for-it.sh", "db:5432", "--", "python", "/app/myapp/manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=myapp.settings
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
